version: "3.8"
services:
  db:
    image: postgres:13.3-alpine
    env_file:
      - .env
    # environment:
    #   POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
  app:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - .:/workdir
    ports:
      - "8080:8080"
    depends_on:
      - db
