[package]
edition = "2018"
name = "project"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.4.0"
actix-web = "3"
juniper = "0.14.2"
serde = "1.0.103"
serde_derive = "1.0.103"
serde_json = "1.0.44"
